package com.example.mcpclient.controller;

import com.example.mcpclient.service.ChatService;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import reactor.core.publisher.Flux;

/**
 * Chat REST Controller
 *
 * Provides REST API endpoints for interacting with the AI assistant.
 * All endpoints leverage the MCP-connected ChatClient, meaning the LLM
 * has access to all tools exposed by the MCP server.
 *
 * Uses Java records for request/response types — the modern, concise
 * alternative to raw Maps or verbose POJO classes.
 *
 * Endpoints:
 * - POST /chat          → Single-turn chat (request/response)
 * - POST /chat/stream   → Streaming chat (SSE token-by-token)
 * - POST /chat/system   → Chat with custom system instruction
 */
@RestController
@RequestMapping("/chat")
public class ChatController {

    // ── Request / Response records ────────────────────────────────────────────

    public record ChatRequest(String message) {}

    public record ChatResponse(String response) {}

    public record SystemChatRequest(String system, String message) {}

    public record ErrorResponse(String error) {}

    // ─────────────────────────────────────────────────────────────────────────

    private final ChatService chatService;

    public ChatController(ChatService chatService) {
        this.chatService = chatService;
    }

    /**
     * Single-turn chat endpoint.
     *
     * Example:
     *   curl -X POST http://localhost:8080/chat \
     *     -H "Content-Type: application/json" \
     *     -d '{"message": "What is the weather in Tokyo?"}'
     */
    @PostMapping
    public ResponseEntity<?> chat(@RequestBody ChatRequest request) {
        if (request.message() == null || request.message().isBlank()) {
            return ResponseEntity.badRequest().body(new ErrorResponse("Message cannot be empty"));
        }
        return ResponseEntity.ok(new ChatResponse(chatService.chat(request.message())));
    }

    /**
     * Streaming chat endpoint using Server-Sent Events.
     * Tokens are sent as they are generated by the LLM.
     *
     * Example:
     *   curl -N http://localhost:8080/chat/stream \
     *     -H "Content-Type: application/json" \
     *     -d '{"message": "Tell me about the employees in the database"}'
     */
    @PostMapping(value = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
    public Flux<String> chatStream(@RequestBody ChatRequest request) {
        return chatService.chatStream(request.message() != null ? request.message() : "");
    }

    /**
     * Chat with a custom system instruction.
     * Allows overriding the default system prompt for specific use cases.
     *
     * Example:
     *   curl -X POST http://localhost:8080/chat/system \
     *     -H "Content-Type: application/json" \
     *     -d '{
     *       "system": "You are a SQL expert. Always respond with SQL queries.",
     *       "message": "Show me all employees earning more than 130000"
     *     }'
     */
    @PostMapping("/system")
    public ChatResponse chatWithSystem(@RequestBody SystemChatRequest request) {
        return new ChatResponse(
                chatService.chatWithSystem(
                        request.system() != null ? request.system() : "",
                        request.message() != null ? request.message() : ""
                )
        );
    }
}
